package gt.lupa.http;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import gt.lupa.config.ServerConfig;
import gt.lupa.storage.ClasspathCatalogSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.time.Duration;
import java.util.LinkedHashMap;
import java.util.Map;
import static org.junit.jupiter.api.Assertions.*;

class NioHttpServerIntegrationTest {
    private NioHttpServer server;private int port;
    @BeforeEach void start()throws Exception{ServerConfig c=new ServerConfig("127.0.0.1",0,"fixture",Path.of("data/catalog.json"),16*1024,32,4,32,2,Duration.ofMillis(350),1024*1024,256*1024);server=new NioHttpServer(c,new HttpRouter(ClasspathCatalogSource.defaultFixture()));server.start();port=server.port();}
    @AfterEach void stop(){if(server!=null)server.close();}
    @Test void getRootAssetsAndCatalogUseLocalRepresentationsAndCorrectMime()throws Exception{RawResponse root=request("GET / HTTP/1.1\r\nHost: localhost\r\n\r\n");assertEquals(200,root.status);assertTrue(root.text().contains("Servidor HTTP asíncrono E19 activo"));assertEquals(root.body.length,root.contentLength());assertTrue(root.header("content-type").startsWith("text/html"));RawResponse css=request("GET /assets/app.css HTTP/1.1\r\nHost: localhost\r\n\r\n");assertEquals(200,css.status);assertTrue(css.header("content-type").startsWith("text/css"));RawResponse js=request("GET /assets/app.js HTTP/1.1\r\nHost: localhost\r\n\r\n");assertEquals(200,js.status);assertTrue(js.header("content-type").startsWith("text/javascript"));assertFalse(js.text().contains("http://"));assertFalse(js.text().contains("https://"));RawResponse catalog=request("GET /api/catalog HTTP/1.1\r\nHost: localhost\r\n\r\n");assertEquals(200,catalog.status);JsonNode json=new ObjectMapper().readTree(catalog.body);assertEquals(1,json.get("schemaVersion").asInt());assertEquals("lupa-small",json.get("images").get(0).get("imageId").asText());assertNull(json.get("images").get(0).get("path"));}
    @Test void headKeepsGetHeadersAndSendsNoBodyIncludingErrors()throws Exception{RawResponse get=request("GET / HTTP/1.1\r\nHost: localhost\r\n\r\n"),head=request("HEAD / HTTP/1.1\r\nHost: localhost\r\n\r\n");assertEquals(200,head.status);assertEquals(get.header("content-type"),head.header("content-type"));assertEquals(get.header("content-length"),head.header("content-length"));assertEquals(0,head.body.length);RawResponse missing=request("HEAD /does-not-exist HTTP/1.1\r\nHost: localhost\r\n\r\n");assertEquals(404,missing.status);assertTrue(missing.contentLength()>0);assertEquals(0,missing.body.length);}
    @Test void invalidRoutesMethodsPrivatePathsAndReservedLupaAreExplicit()throws Exception{assertEquals(404,request("GET /missing HTTP/1.1\r\nHost: localhost\r\n\r\n").status);RawResponse method=request("POST / HTTP/1.1\r\nHost: localhost\r\nContent-Length: 0\r\n\r\n");assertEquals(405,method.status);assertEquals("GET, HEAD",method.header("allow"));assertEquals(404,request("GET /data/originals/secret.jpg HTTP/1.1\r\nHost: localhost\r\n\r\n").status);assertEquals(404,request("GET /.git/config HTTP/1.1\r\nHost: localhost\r\n\r\n").status);assertEquals(426,request("GET /lupa HTTP/1.1\r\nHost: localhost\r\nUpgrade: websocket\r\n\r\n").status);}
    @Test void rejectsHostFramingTraversalEncodingAndOversizedHeaders()throws Exception{assertEquals(400,request("GET / HTTP/1.1\r\n\r\n").status);assertEquals(400,request("GET / HTTP/1.1\r\nHost: localhost\r\nContent-Length: 1\r\n\r\n").status);assertEquals(400,request("GET / HTTP/1.1\r\nHost: localhost\r\nTransfer-Encoding: chunked\r\n\r\n").status);assertEquals(400,request("GET /%2e%2e/secret HTTP/1.1\r\nHost: localhost\r\n\r\n").status);assertEquals(400,request("GET /%ZZ HTTP/1.1\r\nHost: localhost\r\n\r\n").status);String huge="GET / HTTP/1.1\r\nHost: localhost\r\nX-Huge: "+"a".repeat(17000)+"\r\n\r\n";assertEquals(431,request(huge).status);}
    @Test void fragmentedHeadersCompleteAcrossTerminatorBoundary()throws Exception{try(Socket socket=connect()){socket.getOutputStream().write("GET /api/catalog HTTP/1.1\r\nHost: local".getBytes(StandardCharsets.ISO_8859_1));socket.getOutputStream().flush();socket.getOutputStream().write("host\r\nX: y\r\n\r".getBytes(StandardCharsets.ISO_8859_1));socket.getOutputStream().flush();socket.getOutputStream().write("\n".getBytes(StandardCharsets.ISO_8859_1));socket.getOutputStream().flush();assertEquals(200,RawResponse.parse(readAll(socket)).status);}}
    @Test void oneIncompleteClientDoesNotBlockAnotherAndTimeoutIsBounded()throws Exception{try(Socket slow=connect()){slow.getOutputStream().write("GET / HTTP/1.1\r\nHost: localhost\r\n".getBytes(StandardCharsets.ISO_8859_1));slow.getOutputStream().flush();assertEquals(200,request("GET / HTTP/1.1\r\nHost: localhost\r\n\r\n").status);assertEquals(408,RawResponse.parse(readAll(slow)).status);}}
    @Test void disconnectsAndPipelinedInputDoNotBreakAcceptLoopOrProduceSecondResponse()throws Exception{try(Socket abandoned=connect()){abandoned.getOutputStream().write("GET / HTTP/1.1\r\nHost:".getBytes(StandardCharsets.ISO_8859_1));}assertEquals(200,request("GET / HTTP/1.1\r\nHost: localhost\r\n\r\n").status);String two="GET / HTTP/1.1\r\nHost: localhost\r\n\r\nGET /api/catalog HTTP/1.1\r\nHost: localhost\r\n\r\n";byte[] bytes=exchange(two);String wire=new String(bytes,StandardCharsets.ISO_8859_1);assertEquals(1,occurrences(wire,"HTTP/1.1 "));assertTrue(wire.startsWith("HTTP/1.1 200")||wire.startsWith("HTTP/1.1 400"));assertEquals(200,request("GET / HTTP/1.1\r\nHost: localhost\r\n\r\n").status);}
    private RawResponse request(String request)throws Exception{return RawResponse.parse(exchange(request));}private byte[] exchange(String request)throws Exception{try(Socket socket=connect()){socket.getOutputStream().write(request.getBytes(StandardCharsets.ISO_8859_1));socket.getOutputStream().flush();return readAll(socket);}}private Socket connect()throws IOException{Socket s=new Socket();s.connect(new InetSocketAddress("127.0.0.1",port),1000);s.setSoTimeout(2000);return s;}private static byte[] readAll(Socket s)throws IOException{ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[4096];int n;while((n=s.getInputStream().read(b))!=-1)out.write(b,0,n);return out.toByteArray();}private static int occurrences(String text,String needle){int count=0;for(int at=0;(at=text.indexOf(needle,at))>=0;at+=needle.length())count++;return count;}
    private static final class RawResponse{final int status;final Map<String,String> headers;final byte[] body;RawResponse(int status,Map<String,String> headers,byte[] body){this.status=status;this.headers=headers;this.body=body;}static RawResponse parse(byte[] bytes){String wire=new String(bytes,StandardCharsets.ISO_8859_1);int split=wire.indexOf("\r\n\r\n");assertTrue(split>=0,"response did not contain complete headers");String[] lines=wire.substring(0,split).split("\r\n");int status=Integer.parseInt(lines[0].split(" ")[1]);Map<String,String> headers=new LinkedHashMap<>();for(int i=1;i<lines.length;i++){int colon=lines[i].indexOf(':');headers.put(lines[i].substring(0,colon).toLowerCase(),lines[i].substring(colon+1).trim());}return new RawResponse(status,headers,java.util.Arrays.copyOfRange(bytes,split+4,bytes.length));}String header(String name){return headers.get(name.toLowerCase());}int contentLength(){return Integer.parseInt(header("content-length"));}String text(){return new String(body,StandardCharsets.UTF_8);}}
}
