suiteStartedAt=2026-10-04T01:21:41-06:00
commit=c9c7f0a19095d635486d52c0e2f8ab78d3e3e25b
workloads=stable,aggressive
repetitions=5
measuredRunsPerWorkload=60
expectedMeasuredRunsTotal=120
suiteFailures=0
