package gt.lupa.storage;

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.regex.Pattern;

public final class CatalogValidator {
    private static final Pattern IMAGE_ID=Pattern.compile("^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$");private static final Pattern VERSION=Pattern.compile("^v[1-9][0-9]{0,9}$");private CatalogValidator(){}
    public static CatalogSnapshot validate(CatalogSnapshot c)throws CatalogException{if(c==null)throw new CatalogException("catalog is null");if(c.schemaVersion()!=1)throw new CatalogException("unsupported catalog schemaVersion");if(c.images()==null)throw new CatalogException("images is required");Set<String> ids=new HashSet<>();for(CatalogImage i:c.images()){validateId(i.imageId());validateVersion(i.imageVersion());if(i.width()<=0||i.height()<=0)throw new CatalogException("image dimensions must be positive");if(i.tileSize()!=256)throw new CatalogException("tileSize must be 256");if(i.maxLevel()<0)throw new CatalogException("maxLevel must be nonnegative");if(!ids.add(i.imageId()))throw new CatalogException("duplicate imageId in catalog");}return new CatalogSnapshot(1,List.copyOf(c.images()));}
    public static ImageManifest validateManifest(ImageManifest m)throws CatalogException{if(m==null)throw new CatalogException("manifest is null");if(m.schemaVersion()!=1)throw new CatalogException("unsupported manifest schemaVersion");validateId(m.imageId());validateVersion(m.imageVersion());if(m.width()<=0||m.height()<=0)throw new CatalogException("manifest dimensions must be positive");if(m.tileSize()!=256||m.overlap()!=0||!"onetile".equals(m.depth()))throw new CatalogException("manifest tile parameters do not match LUPA v1");if(m.levels()==null||m.levels().isEmpty())throw new CatalogException("manifest levels are required");int max=m.levels().size()-1;for(int i=0;i<m.levels().size();i++){ImageLevel level=m.levels().get(i);if(level.z()!=i||level.width()<=0||level.height()<=0)throw new CatalogException("invalid manifest level sequence");if(level.width()!=dimensionAt(m.width(),max,i)||level.height()!=dimensionAt(m.height(),max,i))throw new CatalogException("manifest level dimensions are inconsistent");}ImageLevel first=m.levels().getFirst(),last=m.levels().getLast();if(first.width()>256||first.height()>256)throw new CatalogException("level 0 must fit one tile");if(last.width()!=m.width()||last.height()!=m.height())throw new CatalogException("final level must match original dimensions");return new ImageManifest(m.schemaVersion(),m.imageId(),m.imageVersion(),m.width(),m.height(),m.tileSize(),m.overlap(),m.depth(),List.copyOf(m.levels()));}
    public static void validateId(String id)throws CatalogException{if(id==null||!IMAGE_ID.matcher(id).matches())throw new CatalogException("invalid imageId");}public static void validateVersion(String v)throws CatalogException{if(v==null||!VERSION.matcher(v).matches())throw new CatalogException("invalid imageVersion");}
    private static int dimensionAt(int original,int maxLevel,int z){int shifts=maxLevel-z;long divisor=1L<<shifts;return(int)((original+divisor-1)/divisor);}
}
